const fs = require('fs');
const path = require('path');

// Read version from package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

// Generate src/version.ts for direct import
const versionTsContent = `// Auto-generated by scripts/inject-version.cjs
// Do not edit manually - updated on each release
export const APP_VERSION = '${version}';
`;

const versionTsPath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(versionTsPath, versionTsContent);
console.log(`Version ${version} injected into src/version.ts`);

// Generate public/version.json for runtime version checking
const versionJsonContent = JSON.stringify({ version }, null, 2) + '\n';
const versionJsonPath = path.join(__dirname, '..', 'public', 'version.json');
fs.writeFileSync(versionJsonPath, versionJsonContent);
console.log(`Version ${version} written to public/version.json`);
